swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

paths:
  /dogs:
    get:
      operationId: api.dog.read_all
      tags:
        - Dogs
      summary: Read the entire dogs list
      description: Read the entire dogs list
      parameters:
        - name: limit
          in: query
          type: integer
          description: Limit the number of dogs returned by the query
          required: false
      responses:
        200:
          description: Successfully read dogs list operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Dog'
    post:
      operationId: api.dog.create
      tags:
        - Dogs
      summary: Create a new dog in the dogs list
      description: Create a new dog in the dogs list
      parameters:
        - name: dog
          in: body
          description: Dog to create
          required: True
          schema:
            $ref: '#/definitions/Dog'
      responses:
        201:
          description: Successfully created dog operation
  /dogs/{id_}:
    get:
      operationId: api.dog.read_one
      tags:
        - Dogs
      summary: Read one dog from the dogs list
      description: Read one dog from the dogs list
      parameters:
        - name: id_
          in: path
          type: integer
          description: ID of the dog
          required: True
      responses:
        200:
          description: Successfully read dogs list operation
          schema:
            $ref: '#/definitions/Dog'
    put:
      operationId: api.dog.update
      tags:
        - Dogs
      summary: Update a dog in the dogs list
      description: Update a dog in the dogs list
      parameters:
        - name: id_
          in: path
          description: ID of the dog
          type: integer
          required: True
        - name: dog
          in: body
          schema:
            $ref: '#/definitions/Dog'
      responses:
        200:
          description: Successfully update dog operation
    delete:
      operationId: api.dog.delete
      tags:
        - Dogs
      summary: Delete a dog from the dogs list
      description: Delete a dog from the dogs list
      parameters:
        - name: id_
          in: path
          type: integer
          required: True
      responses:
        200:
          description: Successfully delete dog operation

definitions:
  Dog:
      type: object
      required:
        - name
        - age
      properties:
        id:
          type: integer
          format: int32
          readOnly: true
        name:
          type: string
        age:
          type: integer